env:
  browser: true
  commonjs: false
  es6: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  no-console: 0
  no-async-promise-executor: 0
